scrape_configs:
  - job_name: 'metr101-service'
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['backend-core:3000', 'tools-backend:3000']
